apiVersion: v1
kind: Service
metadata:
  name: node-project
spec:
  selector:
    app: nodeproject
  ports:
    - name: http
      protocol: TCP
      port: 3005
      targetPort: 3005
  type: LoadBalancer
